<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-URKGA8H" name="testCases.Facility" tests="21" failures="0" timestamp="24 Jul 2018 12:23:47 GMT" time="429.098" errors="1">
  <testcase name="Tc_Patterns_02" time="24.194" classname="testCases.Facility"/>
  <testcase name="Tc_Phy_04" time="20.345" classname="testCases.Facility"/>
  <testcase name="Tc_Fac_01" time="35.545" classname="testCases.Facility"/>
  <testcase name="Tc_Fac_02" time="13.990" classname="testCases.Facility"/>
  <testcase name="Tc_Phy_05" time="33.644" classname="testCases.Facility"/>
  <testcase name="Tc_Manufacturers_02" time="12.013" classname="testCases.Facility"/>
  <testcase name="Tc_Fac_03" time="15.873" classname="testCases.Facility"/>
  <testcase name="Tc_Dep_06" time="29.922" classname="testCases.Facility"/>
  <testcase name="Tc_GL_Code_04_05" time="35.898" classname="testCases.Facility"/>
  <testcase name="Tc_Dep_07" time="21.214" classname="testCases.Facility"/>
  <testcase name="Tc_Patterns_01_03" time="19.295" classname="testCases.Facility"/>
  <testcase name="Tc_Manufacturers_01" time="9.507" classname="testCases.Facility"/>
  <testcase name="Tc_GL_Code_01_02" time="18.187" classname="testCases.Facility"/>
  <testcase name="Tc_Patterns_06" time="8.449" classname="testCases.Facility">
    <error type="java.lang.NumberFormatException" message="For input string: &quot;1532434118096&quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: "1532434118096"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at testCases.Facility.Tc_Patterns_06(Facility.java:767)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Tc_Patterns_06 -->
  <testcase name="Tc_Phy_01_02_03" time="28.327" classname="testCases.Facility"/>
  <testcase name="Tc_Dep_03_04" time="36.335" classname="testCases.Facility"/>
  <testcase name="Tc_Fac_04" time="14.618" classname="testCases.Facility"/>
  <testcase name="Tc_Phy_01" time="11.968" classname="testCases.Facility"/>
  <testcase name="Tc_ManageApprovalFlow_01" time="9.415" classname="testCases.Facility"/>
  <testcase name="Tc_Patterns_05" time="13.326" classname="testCases.Facility"/>
  <testcase name="Tc_Fac_05_Dep_02" time="17.033" classname="testCases.Facility"/>
</testsuite> <!-- testCases.Facility -->
